server:
  port: 8080
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

# Expose all management related actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

metrics:
  tags:
    application:${spring.application.name}

logging:
  level:
    com:
      nainesh:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 #no of requests to monitor before changing from closed to open
      permittedNumberOfCallsInHalfOpenState: 2 #2 requests can be allowed to half open to decide next state change
      failureRateThreshold: 50 #50% fail, then move to open state
      waitDurationInOpenState: 10000 #Wait 10s