spring:
  config:
    activate:
      on-profile: "tst"

build:
  version: "2.0"

cards:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Nainesh Goel - TSTer"
    email: "tst@nainesh.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371