server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_tst.yml"
      - "application_prd.yml"
  profiles:
    active:
      - "prd"

build:
  version: "3.0"

cards:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "Nainesh Goel - Developer"
    email: "dev@nainesh.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345