spring:
  config:
    activate:
      on-profile: "tst"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related tst APIs "
  contactDetails:
    name: "Nainesh Goel - QA"
    email: "goel@nainesh.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345