server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prd"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update #If no tables create new tables, on basis on startup provided sql instructions
    show-sql: true #print sql queries in console
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# Expose all management related actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"